### ISSUE TITLE
Experiment-C programs

### ISSUE THREAD

**Issue by nguyenthanhvuh** [unsat/dig#1]
- [ ] Run Dig on C programs (e.g., Hola), look at the results, and then do some quick comparison with the corresponding Java ones.  
- [ ] Create a table showing the programs,  the time difference btw the Java and C, and the number of inferred invariants (especially the important invariants).

**Comment by ishimwed** [comment]
I do not understand invariants of form **lambda i,j,flag: min(flag, j) - i <= 0**

**Comment by ishimwed** [comment]
44.dig.c and H36.java and H34.java do not run 
42.dig.c and H42.java and 34.dig.c: DIG generated invariants are not strong enough to imply the formula in the assert

**Comment by nguyenthanhvuh** [comment]
that means
min(flag,j) <= i
if flag <= j  then flag <=i  else j <= i
or flag <=i or j <= i

**Comment by nguyenthanhvuh** [comment]
> I do not understand invariants of form **lambda i,j,flag: min(flag, j) - i <= 0**

**Comment by nguyenthanhvuh** [comment]
> 44.dig.c and H36.java and H34.java do not run
> 42.dig.c and H42.java and 34.dig.c: DIG generated invariants are not strong enough to imply the formula in the assert

it is known that Dig/Syminfer cannot infer sufficiently strong invariants for some of these programs (e.g., 01, 21, 42),  and cannot generate invariants for others (e.g., 24, 27).   It should be able to generate sufficient strong invs for all others.

**Comment by nguyenthanhvuh** [comment]
could you do a `git pull` ?  I've updated some files though they do not seem to affect these files that fail to run.

**Comment by ishimwed** [comment]
> could you do a `git pull` ? I've updated some files though they do not seem to affect these files that fail to run.

Done

**Comment by ishimwed** [comment]
> Did you get anything for 34.dig.c ?
The invariant generated by DIG are not strong enough. But I might have expressed the if block wrong when using z3.
Dig invariants:
1. x^2 - 4*x*y + 4*y^2 - x + 2*y == 0
2. n*x - 4*x*y + 4*y^2 - x + 2*y == 0
3. m - 10 == 0
4. i - x == 0
5. -i <= 0
6. -i + n <= 0
Expected invariant: if (m==i) x=2*y

**Comment by nguyenthanhvuh** [comment]
Is that location in then branch of  if(m==i) even reachable?

**Comment by ishimwed** [comment]
> Is that location in then branch of if(m==i) even reachable?

It is reachable when n=10. 
However, the invariants I mentioned earlier where from location right before the if block

**Comment by ishimwed** [comment]
For 32.dig.c (the one that is failing to obtain symbolic states) civl runs and produce the path condition to be "true" when no max depth is provided. When maxdepth is provided no path condition is produced

**Comment by nguyenthanhvuh** [comment]
That’s strange, if you increase the max-depth then does it work ?  Also, we want more than just the path condition over input variables right ?  we also want the symbolic states for every other variables.  Can you use Civl by hand to generate the symbolic states?

**Comment by ishimwed** [comment]
> That’s strange, if you increase the max-depth then does it work ? Also, we want more than just the path condition over input variables right ? we also want the symbolic states for every other variables. Can you use Civl by hand to generate the symbolic states?

The smallest maxdepth for which civl produces path condition (which is just "true") is 404
