### ISSUE TITLE
Experiment-Java programs

### ISSUE THREAD

**Issue by nguyenthanhvuh** [unsat/dig#2]
Let's rerun the experiments to get the results like those in Tab 1 in the SymInfer paper https://cse.unl.edu/~tnguyen/pubs/symtraces.pdf .  Create a note that talk about anything interesting (e.g., programs that do not work, those that consistently give some strange invariants, etc)  

0. In the SymInfer paper, read from the beginning of Section 5 up to (and including) 5B:  Analyzing Program Correctness to see how the experiment was done.  

1. Run `dig` on some of the NLA programs several times ,  e.g., CohenDiv,  Ps4, etc so that you have a feel on what the results would look like.  Each of these programs should have nonlinear invs at the considered locations (e.g., in CohenDiv, we have `a*y + r == x`, etc).  Analyze Dig's results to see that it does give these invariants.  

2.  Identify programs that do not work:  look at Tab 1 in the SymInfer paper,  some of these do not work,  run those and confirm that they do not work.  Then create a new directory and move programs that do not work there.  In the notes, mentioned these programs and reasons why they do not work (e.g., takes a long time on some parts .. look at the log, see what parts it get stuck on)

3. Run `dig` on all of these programs,  there's a script called `benchmark.py` in the `main` src dir, you can run them like this 
```
f=../results/nla_010220 ; rm -rf $f; python benchmark.py 2>&1 | tee $f    
```
4. We want to collect results similar to those in Tab 1 (e.g., time, # of invs).  We also want to show how many of the obtained invariants are nonlinear, oct, and max/min-plus.

**Comment by ishimwed** [comment]
For CohenDiv.java the paper says you got invariants at 2 locations but the the current CohenDiv.java traces three location.

**Comment by ishimwed** [comment]
table 1 has V, T, D column. It says T is the number of terms. What are terms?

**Comment by nguyenthanhvuh** [comment]
terms are things like   x,y,z,xy,yz,xz  ,  in the output of Dig you should
see it somewhere.

**Comment by ishimwed** [comment]
For some programs that do not produce invariants, I am having trouble understanding the JPF output for them

**Comment by ishimwed** [comment]
> Identify programs that do not work: look at Tab 1 in the SymInfer paper, some of these do not work, run those and confirm that they do not work. Then create a new directory and move programs that do not work there. In the notes, mentioned these programs and reasons why they do not work (e.g., takes a long time on some parts .. look at the log, see what parts it get stuck on)

All programs that failed in table 1 still fail.
**Note:** Egcd2.java works when generating invariants at the end of the program but fails when generating invariants in the loop. 16 invariants generated; highest degree is 5; 7 variables used, 18 terms in 4.22 seconds

**Comment by ishimwed** [comment]
For number of invariants in table 1, do you count distinct invariants if multiple locations. There are invariants that come up in more than one location.

**Comment by nguyenthanhvuh** [comment]
I do because they occur at different locations.

**Comment by ishimwed** [comment]
> Run dig on all of these programs, there's a script called benchmark.py in the main src dir, you can run them like this
f=../results/nla_010220 ; rm -rf $f; python benchmark.py 2>&1 | tee $f  

there is no folder named results ../results/nla_010220

**Comment by nguyenthanhvuh** [comment]
Other than the below programs in the failToRun dir,  any other ones that have problems running?  
It is expected that Dig can't run these 6 programs (the SymInfer paper also that they cannot be run sucessfully).  

tests/failedToRun/Egcd2.java
tests/failedToRun/Egcd3.java
tests/failedToRun/Freire1.java
ttests/failedToRun/Freire2.java
tests/failedToRun/Geo3.java
tests/failedToRun/Knuth.java

**Comment by nguyenthanhvuh** [comment]
I've updated some files, could you pull?    I remember you said `ProdBin` has a problem?  I think it is now fixed.  What other files (other than the 6 expected ones) have problems?  
- Before reporting the error about running `somefile.java` to me,  could you check
   1.  there's a new directory in `test` called SymInferASE  ,  go in there and find the same `somefile.java` file and see if there's any diff btw the two (e.g., missing a precondition).  If there is, try to make the one you have a problem with looks like the one in SymInferASE, rerun and see if it fixes the problem.  If it does, please mark a comment to the one you modified so we remember.

**Comment by ishimwed** [comment]
> Other than the below programs in the failToRun dir, any other ones that have problems running?
> It is expected that Dig can't run these 6 programs (the SymInfer paper also that they cannot be run sucessfully).
> 
> tests/failedToRun/Egcd2.java
> tests/failedToRun/Egcd3.java
> tests/failedToRun/Freire1.java
> ttests/failedToRun/Freire2.java
> tests/failedToRun/Geo3.java
> tests/failedToRun/Knuth.java

There are some programs that failed expected to work. For example, sqrt.java. I will have a report about all of them by the end of tomorrow. I left my notebook at school

**Comment by nguyenthanhvuh** [comment]
I’ve just fixed that issue, turns out that it’s missing a precondition.  Do a git pull and check again.  Also I left some comments on github issue on how to find and fix similar problems (e.g., checking if it’s missing some precondition from the reference file in the new SymInferASE dir).

**Comment by ishimwed** [comment]
> I've updated some files, could you pull? I remember you said `ProdBin` has a problem? I think it is now fixed. What other files (other than the 6 expected ones) have problems?
> 
> * Before reporting the error about running `somefile.java` to me,  could you check
>   
>   1. there's a new directory in `test` called SymInferASE  ,  go in there and find the same `somefile.java` file and see if there's any diff btw the two (e.g., missing a precondition).  If there is, try to make the one you have a problem with looks like the one in SymInferASE, rerun and see if it fixes the problem.  If it does, please mark a comment to the one you modified so we remember.

I updated the table 1 from the paper. A few programs that were supposed to work failed: Sqrt.java Lcm2.java and Ps6.java. I checked the SymInferASE folder and the program look the same. The vtrace() function is missing in SymInferASE files but I think it's because SymInfer didn't need it. I am still trying to figure out why they failed. Also increased timeout to 8 minutes (in SymInfer paper says 5 minutes).

**Comment by nguyenthanhvuh** [comment]
Did some updates, do a git pull.

I am not sure why Sqrt doesn't work.  I run it several times and it gives the correct results every time.    Same thing with Lcm2.    I have updated PS6 (by adding a precondition) and it should work now.  I also made some changes to the code and it should work with CohenCu.  
Rerun and let me know how everything goes.

**Comment by ishimwed** [comment]
I was able to recreate Table 1. All the files expected to run worked, except Geo3.java. Dig generated invariants but they were not strong enough to imply the known invariant.

**Comment by nguyenthanhvuh** [comment]
Can you tell me the generated invariants and the expected ones?

**Comment by ishimwed** [comment]
> Can you tell me the generated invariants and the expected ones?


Dig generated invariants:
1. z <= 10
2. k <= 10
3. -z <= 0
4. -y <= 0
5. -y + z <= 9
6. -k <= -1
7. -k - y <= -2
Expected invariants:
z*x-x+a-a*z*y == 0

**Comment by nguyenthanhvuh** [comment]
Not sure why you got that ,  this is what I got 

$ time sage -python -O dig.py ../tests/nla/Geo3.java -log 4
...

*** '../tests/nla/Geo3.java', 1 locs, 9 invs (1 Eqt, 1 MP, 7 Oct), 1164 traces, 337 inps, time 89.22s, rand seed 1582516589.49, test 29 15:
vtrace1 (9 invs):
1. a*k*y*z - k*x*z - 10*a*y*z - a*k + k*x + 10*x*z + 10*a - 10*x == 0
2. z <= 10
3. k <= 10
4. -z <= 0
5. -y <= 0
6. -y + z <= 9
7. -k <= -1
8. -k - y <= -2
9. lambda a,x,y: a - max(x, y, 0) <= 0
alg:DEBUG:clean up: rm -rf /var/tmp/Dig_h5h234x6
sage -python -O dig.py ../tests/nla/Geo3.java -log 4  538.84s user 19.38s system 529% cpu 1:45.52 total
