### ISSUE TITLE
Remove trivial disj  in pre/post conds

### ISSUE THREAD

**Issue by nguyenthanhvuh** [unsat/dig#3]
if a -> b is a tautology, then remove it

**Comment by ishimwed** [comment]
Are pre/post conds annotated in programs or are they the invariants generated by dig?
I don't understand exactly what I have to do here

**Comment by nguyenthanhvuh** [comment]
For the complexity programs, pre and post are generated by DIG,  so you would look at the final invariants and check if they make sense.  See the Section 4.3 in the paper that talks about pre/post conds.
