### ISSUE TITLE
Run DIG on C programs

### ISSUE THREAD

**Issue by nguyenthanhvuh** [unsat/dig#7]
Can you run DIG on the C programs in  `/tesst/c` ?    I expect them to have similar results as the Java ones.  You do not need to create a table in the TeX for this,  but do record their results somewhere, e.g., text files.

**Comment by ishimwed** [comment]
> Can you run DIG on the C programs in `/tesst/c` ? I expect them to have similar results as the Java ones. You do not need to create a table in the TeX for this, but do record their results somewhere, e.g., text files.

I run dig on c programs. In general everything is as expected
**Unexpected result:**
In hola the following programs failed to run:
1. 18.dig.c and 32.dig.c because civl cannot produce symstates
2. 20.dig.c and 30.dig.c due to some errors I haven't figured out
